### ISSUE TITLE
running with electron-prebuilt in production

### ISSUE THREAD

**Issue by parro-it** [sindresorhus/electron-is-dev#1]
I think there are some tools that ship only on npm
And use electron-prebuilt to start even in production.

What do you think about checking an env var, like for example debug module does?

**Comment by sindresorhus** [comment]
> And use electron-prebuilt to start even in production.

Do you have an example? Interested in looking into a way to filter those cases out? Maybe look at the full path somehow.

> What do you think about checking an env var, like for example debug module does?

I guess we could also check `process.env.NODE_ENV === 'dev'`, but very few actually set this. I'd rather handle it fully automatic.

**Comment by parro-it** [comment]
Look for example at https://github.com/segmentio/nightmare/blob/master/lib/nightmare.js
Or https://github.com/fraserxu/electron-pdf/blob/master/cli.js
I saw this pattern lot of time:: there is a cli declared in pkg that require electron-prebuilt and then use the returned path to spawn a new electron process.

**Comment by parro-it** [comment]
Anyway when used this way I think the execpath could be different. I have to check which is the returned path of electron-prebuilt

**Comment by parro-it** [comment]
> Interested in looking into a way to filter those cases out?

Sure!

**Comment by parro-it** [comment]
I did some investigation. It's not easy stuff apparently...
`electron-prebuilt` cli does exactly the same thing as the tools I was speaking.
It requires itself, obtaining the path of `electron` runtime executable, then spawn it using `child_process`.

The only idea that come to my mind if that we could find the parent process id of current one,
and if we could find it's path  and arguments, we could check if it is a node process running `electron-prebuilt` cli.

If it is, then the current electron process was run by `electron .` and we could suppose to be in `dev` mode. Otherwise, it was run:

1) by directly invoking the electron native executable - we are in production
2) by invoking any other node script - we are in production.

What do you think of this idea?
Are you aware of some existing module that could retrieve parent process info required?

**Comment by sindresorhus** [comment]
I guess. Sounds a bit convoluted though. I made this with apps in mind.

What about checking if it's run from a global path?

**Comment by parro-it** [comment]
> Sounds a bit convoluted though.

It is indeed...

> What about checking if it's run from a global path?

I think it's bettter to always add any needed tool in `dev-dependecies`, `electron-prebuilt` included.
Another option could be to patch `electron-prebuilt` to make its cli always add a flag arg when running the Electron native executable.

We can then check that flag to discover if Electron was started from `electron-prebuilt` (dev mode) or from a custom one (prod mode)

**Comment by sindresorhus** [comment]
> Another option could be to patch electron-prebuilt to make its cli always add a flag arg when running the Electron native executable.

I like that idea. Let's try that.

**Comment by ungoldman** [comment]
Just a note, `electron-prebuilt` is community supported (not supported by github or the atom/electron team). If you're looking to create an "official" environmental variable similar to `NODE_ENV` you may want to bring it up with the electron team first before trying to get it adopted into `electron-prebuilt`.

**Comment by sindresorhus** [comment]
@ungoldman That's not the intention. We want to detect `electron-prebuilt` specifically. Feel free to bring it up with the Electron team if you want.

**Comment by parro-it** [comment]
Solved by #7
