### ISSUE TITLE
Does not work in forked process.

### ISSUE THREAD

**Issue by dscalzi** [sindresorhus/electron-is-dev#15]
I run one of my modules in a forked process so as to not lag the main UI. Electron is not defined in that process, so the module fails.

```TypeError: Cannot read property 'app' of undefined```

I could add a work around to my code, but it would be much cleaner for this module to support forked processes as it did in 0.3.0.

**Comment by sindresorhus** [comment]
Then it's no longer an Electron environment, but rather vanilla Node.js. That's outside the scope of the module. You can keep using `0.3.0`.
