### ISSUE TITLE
isDev is always true

### ISSUE THREAD

**Issue by kimgysen** [sindresorhus/electron-is-dev#21]
My npm script looks as follows:

```
"start:prod": "cross-env NODE_ENV=production && electron dist/main.js"
```

main.js:

```
import isDev from 'electron-is-dev';

app.on('ready', () => {
  console.log('isDev', isDev);
  if (!isDev) {
    const {session} = require('electron');
    session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
      callback({responseHeaders: `default-src http: ws:`})
    })
  }
  const win = createWindow();
  createMenu(win);
});
```

The console outputs:

> isDev true

I have some trouble understanding the use of this npm package which seems to be used a lot.  
When setting NODE_ENV, I expect just being able to use `process.env.NODE_ENV` in my code  as I'm used to, and it does seem to work.   
Why do we need another environment variable (?). 

My bundle is packaged with webpack, not sure if this may have anything to do with it, but I wouldn't expect it to.  

```
const path = require('path');

module.exports = {
  entry: "./src/server/main.js",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, '../../dist')
  },
  mode: 'production',
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: "babel-loader"
      }
    ]
  },
  node: {
    __dirname: false,
    __filename: false
  },
  target: "electron-main"
};

```

**Comment by sindresorhus** [comment]
Try to log what `electron.app.isPackaged` reports. `electron-is-dev` uses that underneath and it sounds like that is reporting always true for you too, which means the problem is either your build script or Electron itself. If it's Electron, you should open an issue on the Electron issue tracker.

**Comment by danst3in** [comment]
My understanding is that `electron.app.isPackaged` will only return true if you have packaged the file for example with `electron-builder` and then run the Electron app from the executable file that is produced. This has made it time consuming for me to test other items that behave differently in prod vs. dev, but at least that seems to consistently work.

**Comment by kimgysen** [comment]
I am not currently working on this project. I will close this issue for now; if someone else wants to re-open it, feel free.
