### ISSUE TITLE
Cannot read property 'app' of undefined

### ISSUE THREAD

**Issue by techterbium** [sindresorhus/electron-is-dev#22]
The error is the same as seen in [here](https://github.com/sindresorhus/electron-is-dev/issues/20), but I am getting this when running unit tests using jest.

 I have written a small unit test on a file which includes the below line. 

```const isDev = require('electron-is-dev');```

I get the error below:

```TypeError: Cannot read property 'app' of undefined```

Any feedback is much appreciated. thanks.

**Comment by sindresorhus** [comment]
Does it run successfully if you replace `const isDev = require('electron-is-dev');` with `const isDev = true;`?

**Comment by techterbium** [comment]
Yes, it does run successfully.

**Comment by AxelTerizaki** [comment]
I'm having the same issue but when running `tsc --build` from my CI/CD environment.

```
$ npx rimraf "dist" && tsc --build
/builds/karaokemugen/karaokemugen-app/node_modules/electron-is-dev/index.js:4
const app = electron.app || electron.remote.app;
                                         ^
TypeError: Cannot read property 'app' of undefined
    at Object.<anonymous> (/builds/karaokemugen/karaokemugen-app/node_modules/electron-is-dev/index.js:4:45)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/builds/karaokemugen/karaokemugen-app/node_modules/electron-unhandled/index.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
error Command failed with exit code 1.
```

Strangely it works well when just running tsc --build from my dev environment. I didn't import it directly, but it came with electron-unhandled which I'm using.)

Shouldn't `remote` be tested before trying to test `electron.remote.app` just to be sure ?

EDIT: I just saw issue #20 and I'm using Electron 8.0.2, maybe remote got deprecated already there?

**Comment by GiovanH** [comment]
The commit is labeled as fixing the problem, but I'm still experiencing it with the latest version. 

This seems to be the same issue as https://github.com/sindresorhus/electron-is-dev/issues/20, which was closed without explanation.

Here are the results of `console.log('App:', electron.app); console.log('Remote', electron.remote);` in index.js:

```
App: App {
  _events: [Object: null prototype] {
    'certificate-error': [Function],
    'select-client-certificate': [Function],
    quit: [Function],
    'window-all-closed': [Function],
    'will-finish-launching': [Function: bound onceWrapper] { listener: [Function] }
  },
  _eventsCount: 5,
  _maxListeners: undefined,
  commandLine: {
    hasSwitch: [Function: hasSwitch],
    getSwitchValue: [Function: getSwitchValue],
    appendSwitch: [Function: appendSwitch],
    appendArgument: [Function: appendArgument]
  },
  _setDefaultAppPaths: [Function],
  [Symbol(kCapture)]: false
}
Remote undefined
```

Edit: And from the rendering process, the electron object looks like
```
Electron: 
    clipboard: (...)
    contextBridge: (...)
    crashReporter: (...)
    desktopCapturer: (...)
    ipcRenderer: (...)
    nativeImage: (...)
    shell: (...)
    webFrame: (...)
    deprecate: (...)
```

**Comment by ahadcove** [comment]
In Electron V10 enableRemoteModule is false by default.

All you need to do is set it to true:

```
const w = new BrowserWindow({
  webPreferences: {
    enableRemoteModule: true
  }
})
```

**Comment by ahkohd** [comment]
Any plan to provide support for devs who don't want to enable remote module?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/electron-is-dev/releases/tag/v2.0.0
