### ISSUE TITLE
Allow usage in renderer process

### ISSUE THREAD

**Issue by AgainPsychoX** [sindresorhus/electron-is-dev#30]
Feature request: Allow usage in renderer process, or add info to `README.md` how to achieve it.

It could be really useful feature over the default `isPackaged` we have nowadays.

~~I imagine it could be implemented by detecting whenever `index.js` of the module is running in the renderer process and if so, using IPC to get the information.~~

I ended up using this:
```js
const isDev = window.location.hostname == 'localhost' && window.location.protocol.startsWith('http');
```

**Comment by sindresorhus** [comment]
It used to work in the renderer, but because of the removal of `remote`, it's not feasible anymore. I don't plan to add back support.

**Comment by sindresorhus** [comment]
> or add info to README.md how to achieve it.

I don't think this is the place to document this. It's just how you use any main process API in the renderer; IPC.

**Comment by AgainPsychoX** [comment]
I think I found good way of doing it (and without breaking isolation):

```ts
import type { IpcMainEvent } from 'electron';

// declare global {
// 	interface Window {
// 		isDev: boolean | undefined;
// 	}
// }

let _isDev: boolean;

if (typeof process === 'undefined') {
	_isDev = (<any>window)?.isDev || false;
}
else {
	const useEnv = 'ELECTRON_IS_DEV' in process.env;
	_isDev = useEnv && parseInt(process.env.ELECTRON_IS_DEV || '') === 1;

	if (process.type === 'browser') {
		// Avoid importing stuff restricted as main-only.
		const { app, ipcMain, session } = require('electron/main');

		if (!useEnv) {
			_isDev = !app.isPackaged;
		}

		app.once('ready', () => {
			const selected = session.defaultSession;
			const preloads = selected.getPreloads();
			preloads.unshift(__filename);
			selected.setPreloads(preloads);
		});

		ipcMain.on('electron-is-dev', (event: IpcMainEvent, _) => {
			event.returnValue = _isDev;
		});
	}
	else if (process.contextIsolated) {
		// Avoid importing stuff restricted as renderer-only.
		const { ipcRenderer, contextBridge } = require('electron/renderer');

		if (!useEnv) {
			_isDev = ipcRenderer.sendSync('electron-is-dev');
		}

		contextBridge.exposeInMainWorld('isDev', _isDev);
	}
}

export const isDev = _isDev;
export default isDev;
```

Now can import from both main/browser and renderers processes, while API stays as simple as ever.

Notes:
* Using preloaders magic to avoid having users to hook-up stuff themself, like requiring them to always import the module in their own preload script (for side effect of calling the IPC if necessary). 
* I am avoiding cross-importing stuff restricted to only main/only renderer processes, because it can cause errors. 
* Used `process.contextIsolated` instead `process.type === 'renderer'`, because there were errors on electron output. 
* I don't know about type declarations for `window.isDev`, as they would leak to main process, so I left it commented. 
* I haven't done extensive testing, but it seems to work in my case just fine (while developing and after building release, environment variable seems working properly too). 

Any feedback? Can I open pull request? If so, can I use Typescript (add `typescript` to dev deps, use `tsc` emitting `.js` & `.d.ts`)?

**Comment by AgainPsychoX** [comment]
@sindresorhus PTAL

**Comment by sindresorhus** [comment]
That will only work if it's imported in both main and renderer process. It's quite complex to make it reliably work in both and I don't want that complexity here. It's just not worth adding that kind of complexity into each single package. Electron devs made their choice of ruining the DX.

**Comment by AgainPsychoX** [comment]
But... You always use it in main process! It's most important place. Fun fact, ALL people currently are using it in mine process.

Structures like like:
```ts
	// Load the index.html of the app.
	if (isDev) {
		window.loadURL(`http://localhost:${process.env.PORT || 3000}`);
	}
	else {
		window.loadFile(join(__dirname, '../renderer/index.html'));
	}
```
or
```
	// Open the DevTools.
	if (isDev) {
		window.webContents.openDevTools();
	}
```
are super common in main.

Proposed changes adds good, useful feature without changing any API. It would be good reason for using the package over simply using built-in `isPackaged` too. 

I think your argument is invalid. Are you just mad on Electron devs?

**Comment by sindresorhus** [comment]
> You always use it in main process! It's most important place.

You are assuming everyone does the same as you.

> Proposed changes adds good, useful feature without changing any API. It would be good reason for using the package over simply using built-in isPackaged too.

Publish a package. I would be happy to link to it if you intend to actively maintain it.

> I think your argument is invalid. Are you just mad on Electron devs?

No. I'm just not interested in maintaining a lot of complex code. I do think you're complaining in the wrong place though. Bring your arguments to the Electron repo instead. They're the ones that made it super hard to do seemingly simple things.
