### ISSUE TITLE
Deprecate `electron-is-dev`

### ISSUE THREAD

**Issue by ghost** [sindresorhus/electron-is-dev#32]
Electron.js now has a built-in solution called `app.isPackaged`.
Run:
```
npm deprecate electron-is-dev "Use 'app.isPackaged' from electron.js instead of electron-is-dev"
```

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/electron-is-dev#how-is-this-different-than-appispackaged

**Comment by ghost** [comment]
Setting through an environment variable already can be done natively. `process.env.APP_DEBUG === true || app.isPackaged`. This package only occupies space and most people don't use it for the purpose it has nowadays.
