### ISSUE TITLE
Incorrect result if app is executed under a folder with name `electron`

### ISSUE THREAD

**Issue by myst729** [sindresorhus/electron-is-dev#4]
The dev environment check returns `true` if the packaged app is executed from a path that contains `/electron/`.

<img src="https://cloud.githubusercontent.com/assets/519733/21683294/b33fb5e4-d393-11e6-815f-273ddfc432e3.png" width="420" height="383">

The `electron-reload` is one of my dev dependencies, which is required within a `isDev` check.

By the way, an official approach for such use cases is being discussed (https://github.com/electron/electron/issues/7714), looks like they are very close to draw a conclusion, but don't know when the feature will be shipped.

**Comment by parro-it** [comment]
Seems to be a valid issue, why do you close it?

**Comment by parro-it** [comment]
@mist729 you can now force the correct result using the new ELECTRON_IS_DEV env var

**Comment by TimNZ** [comment]
Amazing that this is still broken when electron is in the path.
So many packages depend on this module I now understand why it is breaking a lot of things in my dev.
