### ISSUE TITLE
Should not be dev, but after packing isDev returns true

### ISSUE THREAD

**Issue by djalmaaraujo** [sindresorhus/electron-is-dev#5]
```bash
electron-packager . --productName='My app' --out=dist --prune --overwrite --app-version=0.0.1 --protocol=myprotocol --protocol-name='My App' --version=1.6.2 --platform=darwin --icon=assets/icons/my-icon.icns
```

After packing my app and, isDev returns true, because all my ```(isDev) ? :``` ifs are returning true.

Am I doing something wrong?

Examples in the code:

```js
const SETTINGS = {
  protocol: (isDev) ? 'devmyprotocol' : 'myprotocol',
  baseURL: (isDev) ? 'https://local.myapp/' : 'https://production/'
};
```

After packing, all settings continue to isDev === true.

**Comment by sindresorhus** [comment]
Can you try v0.3.0 and report back if that fixed it?

**Comment by djalmaaraujo** [comment]
Steps to reproduce:

1. Clone the Quick Start repository
$ git clone https://github.com/electron/electron-quick-start

2. Go into the repository
$ cd electron-quick-start

3. Install the dependencies and run
$ npm install

4. Add is Dev to renderer.js
```js
// This file is required by the index.html file and will
// be executed in the renderer process for that window.
// All of the Node.js APIs are available in this process.

const isDev = require('electron-is-dev');
const h1 = document.querySelector('h1');
if (isDev) {
  h1.innerText = 'Running in development';
} else {
  h1.innerText = 'Running in production';
}
```

5. Run Electron Packager
```bash
electron-packager . --productName='My app' --out=dist --prune --overwrite --app-version=0.0.1 --protocol=myprotocol --protocol-name='My App' --version=1.6.2 --platform=darwin
```

@sindresorhus Looks good with the latest version.
![screenshot 2017-07-24 16 42 20](https://user-images.githubusercontent.com/3402/28541355-1848b678-708f-11e7-82ab-b0b09eafac94.png)

**Comment by kevva** [comment]
Sweet, happy to hear it's working now 🎉
