### ISSUE TITLE
Make it possible to override with an environment variable

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/electron-is-dev#6]
Could be useful if you want to force an environment temporarily just to confirm it works. Another use-case is to remove debugging functionality temporarily.

**Comment by kevva** [comment]
`ELECTRON_ENV` might be a good name for this flag?

**Comment by parro-it** [comment]
We discussed this idea on issue #1: fyi, that discussion lead to [this unmerged PR on electron-prebuilt](https://github.com/electron-userland/electron-prebuilt/pull/118) and than [this issue on Electron repo](https://github.com/electron/electron/issues/7714)  that discuss Electron direct support for the `ELECTRON_ENV` variable.

**Comment by sindresorhus** [comment]
@parro-it But that discussion died down. I don't have time to wait for bureaucracy.

@kevva Let's call it `ELECTRON_IS_DEV=1` (true) /`ELECTRON_IS_DEV=0` (false) so not to conflict with an eventual Electron variable.

**Comment by parro-it** [comment]
> @parro-it But that discussion died down. I don't have time to wait for bureaucracy.

I wasn't suggesting to wait for that discussion to settle, just giving some context about the var...
I like `ELECTRON_IS_DEV ` as name

**Comment by kevva** [comment]
> Let's call it ELECTRON_IS_DEV=1 (true) /ELECTRON_IS_DEV=0 (false) so not to conflict with an eventual Electron variable.

Fine with me.
